
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todolist_development
  host: 127.0.0.1
  username: 
  port: 5432

test:
  <<: *default
  database: todolist_test
  host: 127.0.0.1
  username: 
  port: 5432

production:
  <<: *default
  database: todolist_production
